CREATE OR REPLACE PROCEDURE ACTUALIZA_RECORD_SAMPLE (
   NEW_RECORD    RECORDS.SAMPLE%TYPE,
   RECORD_ID      RECORDS.RECORD_ID%TYPE)
IS
BEGIN
   UPDATE RECORDS
      SET SAMPLE = NEW_RECORD
    WHERE RECORD_ID = RECORD_ID;

   DBMS_OUTPUT.PUT_LINE ('DATOS ACTUALIZADOS: ID EMPLEADO '|| RECORD_ID|| 
   'NUEVO RECORD' || NEW_RECORD);
   COMMIT;
END;
--FIN DEL PROCEDIMIENTO ACTUALIZACION

CREATE OR REPLACE FUNCTION VALIDA_RECORD (SAMPLE RECORDS.SAMPLE%TYPE)
   RETURN BOOLEAN
IS
   FLAG   BOOLEAN;
BEGIN
   IF IS NOT NULL
   THEN
      FLAG := TRUE;
   ELSE
      FLAG := FALSE;
   END IF;

   RETURN FLAG;
END;

--FIN DE LA FUNCION

DECLARE
   NORECORD     RECORDS.RECORD_ID%TYPE;
   NUEVORECORD   RECORDS.SAMPLE%TYPE;
BEGIN
   NORECORD := &NORECORD;
   NUEVORECORD := &NUEVORECORD;

   IF VALIDA_RECORD( NUEVORECORD) THEN
      ADMIN1.ACTUALIZA_RECORD_SAMPLE (NORECORD, NUEVORECORD);
   ELSE
      DBMS_OUTPUT.PUT_LINE ('INVALID DATA');
   END IF;

EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.PUT_LINE ('ERROR ');
END;
/