# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('infection_date', models.DateField()),
                ('technique', models.CharField(max_length=20)),
                ('amplification', models.CharField(blank=True, max_length=20)),
                ('hiv', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1)),
                ('tuberculosis', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1)),
                ('diagnostic_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Country')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='HIVType',
            fields=[
                ('hiv_id', models.AutoField(primary_key=True, serialize=False)),
                ('hiv_type', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'hiv_types',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('marital_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('marital_status', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'marital_status',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('contact_info', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('applicant_unit', models.CharField(blank=True, max_length=25)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.MaritalStatus')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('blood_type', models.CharField(max_length=20)),
                ('diabetes', models.CharField(blank=True, max_length=3)),
                ('sample_type', models.CharField(blank=True, max_length=10)),
                ('deceased', models.CharField(max_length=3)),
                ('subtype', models.CharField(blank=True, max_length=30)),
                ('resistance', models.CharField(blank=True, max_length=10)),
                ('children', models.CharField(blank=True, max_length=3)),
                ('children_num', models.IntegerField(blank=True, null=True)),
                ('english', models.CharField(blank=True, max_length=3)),
                ('sexual_preference', models.CharField(blank=True, max_length=20)),
                ('immigration_hist', models.CharField(blank=True, max_length=30)),
                ('insurance', models.CharField(blank=True, max_length=30)),
                ('drug_use', models.CharField(blank=True, max_length=30)),
                ('shared_needles', models.CharField(max_length=3)),
                ('criminal_record', models.CharField(blank=True, max_length=30)),
                ('birth_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.City')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Job')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Country')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('schooling_id', models.AutoField(primary_key=True, serialize=False)),
                ('schooling_level', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'schooling',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('dose', models.CharField(max_length=20)),
                ('mediaction', models.CharField(max_length=100)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Diagnosis')),
            ],
            options={
                'db_table': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='TuberculosisType',
            fields=[
                ('tuberculosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('tuberculosis_type', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'tuberculosis_types',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='schooling',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Schooling'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='hiv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.HIVType'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Record'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tuberculosis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TuberculosisType'),
        ),
    ]
