# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180517_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.City'),
        ),
        migrations.AlterField(
            model_name='record',
            name='children',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='criminal_record',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('P', 'Positive'), ('N', 'Negative')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='drug_use',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='english',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='immigration_hist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='insurance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Job'),
        ),
        migrations.AlterField(
            model_name='record',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Country'),
        ),
        migrations.AlterField(
            model_name='record',
            name='resistance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sample_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sexual_preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='shared_needles',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='subtype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
