# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180525_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='english',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sexual_preference',
            field=models.CharField(blank=True, choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
