# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180526_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_value', models.IntegerField(blank=True, null=True)),
                ('cd4_value', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='record',
            name='deceased',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Record'),
        ),
    ]
