# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180527_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='record_id',
        ),
        migrations.AddField(
            model_name='data',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient'),
            preserve_default=False,
        ),
    ]
