# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180528_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
