# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180528_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_value', models.IntegerField(blank=True, null=True)),
                ('cd4_value', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
